import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class BlogServiceService {

DatosDummy: object[] = [
{"title" : "How to start using driving games" , "subtitle" : "The 16 biggest game download blunders" , "author": "Random" , "date" : "1558340029" , "body" : `12 insane (but true) things about daybreak game companies. What the world would be like if multiplayer games didn't exist. The 10 worst virtual lives in history. 9 problems with video game designers. 18 amazing driving game pictures. 14 great articles about role play costumes. The 16 worst songs about solitaire card games. The 11 best resources for football games. How twitter can teach you about gaming chairs. Why your football game never works out the way you plan.

Why video game makers are killing you. What the world would be like if role play costumes didn't exist. The evolution of solitaire card games. 10 ways gaming laptops can make you rich. 12 ways video game designers are completely overrated. Why chess strategies beat peanut butter on pancakes. 8 amazing deck of card pictures. The complete beginner's guide to video game designers. How car games made me a better person. How twitter can teach you about driving games.

7 ways daybreak game companies could leave you needing a lawyer. How to cheat at virtual lives and get away with it. Why your hidden object game never works out the way you plan. How to start using gaming chairs. Why online virtual worlds beat peanut butter on pancakes. What wikipedia can't tell you about star wars games. Hidden object games by the numbers. 11 insane (but true) things about daybreak game companies. How multiplayer games are making the world a better place. Why do people think chess strategies are a good idea?

19 ways gaming laptops are completely overrated. The 12 worst car games in history. The 16 best chess strategy twitter feeds to follow. Why war strategy games are afraid of the truth. How video game designers aren't as bad as you think. Why the world would end without online virtual worlds. An expert interview about video game makers. Why roulette strategies will make you question everything. How cool math games are the new cool math games. 18 problems with car games.`, "url_img" : "http://2.bp.blogspot.com/-SYoGmXV9jBg/VffLfHpqOmI/AAAAAAAAOGY/HzUjN31k9Us/s1600/games_mortal-combat-x_140K.jpg" , "labels" : "Games, Strategy, Role Playing"},

{"title" : "The best ways to utilize designs" , "subtitle" : "Why you shouldn't eat designer furniture in bed" , "author": "Gamborimbo" , "date" : "1555748029" , "body" : `The only modern living room resources you will ever need. The best ways to utilize landscape architectures. Why modular homes beat peanut butter on pancakes. Why rent houses will change your life. How building made me a better person. Why building is the new black. How chief architects can help you live a better life. 20 insane (but true) things about kitchen designs. The unconventional guide to floor plans. 6 ways house plans are completely overrated.

The evolution of luxury homes. 20 things you don't want to hear about designs. 10 amazing landscape architecture pictures. How kitchen designs changed how we think about death. How interior designs aren't as bad as you think. The unconventional guide to studio apartments. How modern homes are the new modern homes. An expert interview about designer furniture. How kitchen designs are making the world a better place. The 5 worst modern living rooms in history.

17 ideas you can steal from bathroom designs. Why you shouldn't eat living room decor in bed. Why bathroom designs are killing you. 7 ways interior design jobs could leave you needing a lawyer. How bathroom designs changed how we think about death. 16 amazing house plan pictures. Why modern furniture is the new black. Why the world would end without apartment guides. Interior designs in 20 easy steps. The evolution of small house plans.

18 things about interior design ideas your kids don't want you to know. Why you'll never succeed at chief architects. How to start using rent houses. Why house plans should be 1 of the 7 deadly sins. 5 least favorite kitchen planners. 18 facts about interior design jobs that will impress your friends. How to be unpopular in the home decor world. Why architects are afraid of the truth. 9 things that won't happen in kitchen designs. 15 ways studio apartments can find you the love of your life.`, "url_img" : "http://4.bp.blogspot.com/-kZ0YGIrcPSQ/VffFuBsrNbI/AAAAAAAANqU/aqux80ruW7I/s1600/design_birdnest-stadium_185K.jpg" , "labels" : "Design, Apartment, House"},

{"title" : "What experts are saying about culture tips" , "subtitle" : "The 14 worst road trip games in history" , "author": "Baltasar, el Rey Mago" , "date" : "1558253629" , "body" : `The 16 worst culture tips in history. How spa deals make you a better lover. How hollywood got daily deals all wrong. 16 podcasts about travel insurances. How to cheat at vacation packages and get away with it. Why student tours beat peanut butter on pancakes. 19 things you don't want to hear about carnival cruises. 18 least favorite travel advisors. How flight scanners make you a better lover. 6 myths uncovered about cheap tickets.

14 facts about carnival cruises that will impress your friends. What the beatles could learn from daily deals. The 7 best cheap cruise youtube videos. 14 facts about celebrity cruises that'll keep you up at night. How to cheat at travel packages and get away with it. Why travel coupons will change your life. How twitter can teach you about mission trips. The 5 best student tour youtube videos. 16 ideas you can steal from travel insurances. Why the world would end without celebrity cruises.

Why you'll never succeed at family trip ideas. The 19 best resources for daily deals. 11 ways mission trips can make you rich. What wikipedia can't tell you about flight scanners. The complete beginner's guide to trip ideas. Why the world would end without road trip games. 14 amazing cultural note pictures. 12 podcasts about travel insurances. How travel agents can help you predict the future. Why carnival cruises will make you question everything.

The oddest place you will find travel packages. Why culture tips should be 1 of the 7 deadly sins. How spa deals can help you live a better life. Why travel coupons are afraid of the truth. Travel advisors by the numbers. 13 problems with cultural notes. Ways your mother lied to you about cheapest flights. How trip ideas changed how we think about death. The oddest place you will find travel agencies. The evolution of spa deals.`, "url_img" : "http://2.bp.blogspot.com/-ALRTUnRCWRI/VffVeOiKx4I/AAAAAAAAO6A/V2BR0JpiMnE/s1600/travel_lost-memory-of-childhood_174K.jpg" , "labels" : "Travel, Activities"},

{"title" : "The 16 biggest game download blunders" , "subtitle" : "Expose: you're losing money by not using role play costumes" , "author": "El friki de la esquina" , "date" : "1557735562" , "body" : `How to cheat at game downloads and get away with it. 17 bs facts about gaming chairs everyone thinks are true. 5 movies with unbelievable scenes about video game designers. What everyone is saying about hidden object games. How game jobs can help you live a better life. 11 podcasts about video game makers. 15 least favorite virtual lives. The 6 best video game software youtube videos. Why game websites are on crack about game websites. Why the world would end without virtual lives.

Will online virtual worlds ever rule the world? Why cartoon network games are the new black. The 13 worst songs about car games. Why your game creator never works out the way you plan. An expert interview about solitaire card games. 20 ways cool math games can find you the love of your life. What the beatles could learn from cool math games. 20 bs facts about role play costumes everyone thinks are true. Why you shouldn't eat role play costume in bed. The best ways to utilize video game makers.

An expert interview about star wars games. The only game website resources you will ever need. If you read one article about online virtual worlds read this one. Why video game software beats peanut butter on pancakes. Deck of cards in 5 easy steps. Will deck of cards ever rule the world? Why role play scenarios are killing you. How cartoon network games are making the world a better place. 8 amazing cool math game pictures. 11 facts about free online games that will impress your friends.

14 podcasts about solitaire card games. 12 problems with gaming laptops. How game creators can make you sick. The 5 best game website twitter feeds to follow. Why the world would end without game jobs. 5 ideas you can steal from game creators. The only star wars game resources you will ever need. 5 myths uncovered about game jobs. Why your car game never works out the way you plan. 13 things that won't happen in gaming laptops.`, "url_img" : "http://2.bp.blogspot.com/-XZOf2q4H-rQ/VffLfslrUZI/AAAAAAAAOG4/fu05zVfVwI0/s1600/games_new-star-wars-battlefront_197K.jpg" , "labels" : "Games, Strategy, Role Playing"},

{"title" : "How healthy cooking tips are making the world a better place" , "subtitle" : "The complete beginner's guide to breakfast ideas" , "author": "Amanda Knox" , "date" : "1526804362" , "body" : `How safe food handling tips aren't as bad as you think. 11 ways healthy snacks can make you rich. 10 podcasts about foodstuffs. 9 podcasts about healthy cooking tips. 14 podcasts about healthy cooking tips. The 15 worst songs about chef uniforms. 18 ideas you can steal from minute meals. 8 bs facts about delicious food everyone thinks are true. Why food networks are the new black. 11 things that won't happen in mexican food.

The only dinner idea resources you will ever need. Why chicken dishes are on crack about chicken dishes. Unbelievable snack success stories. 19 things that won't happen in dish reviews. How chicken dishes can help you predict the future. The evolution of delicious magazines. Why snacks are on crack about snacks. Unbelievable healthy lunch idea success stories. Why our world would end if easy meals disappeared. The 6 best resources for chefs.

6 podcasts about whole foods markets. 11 movies with unbelievable scenes about meatloaf recipes. What the world would be like if restaurants didn't exist. 9 things about easy meals your kids don't want you to know. How fast food made me a better person. How to start using breakfast casseroles. How food stamps make you a better lover. How safe food handling tips make you a better lover. The 9 best resources for food processors. The 9 best resources for healthy cooking tips.

How breakfast casseroles aren't as bad as you think. Why food processors are the new black. Why delicious food is killing you. 8 facts about mexican food that'll keep you up at night. Why our world would end if whole foods markets disappeared. The 14 best resources for restaurant weeks. Why restaurants beat peanut butter on pancakes. Why food stamps will make you question everything. Whole foods markets by the numbers. The 13 worst recipes in history.`, "url_img" : "http://4.bp.blogspot.com/-CBy6qKKjlHg/VffJTqYTU5I/AAAAAAAAN6Q/Y46qQgmxVWI/s1600/food_honey-toast_437K.jpg" , "labels" : "Food, Lunch, Chef, Restaurant, Recipe"},

{"title" : "Why your photography award never works out the way you plan" , "subtitle" : "20 ways cutest baby contests could leave you needing a lawyer" , "author": "Padre Prado" , "date" : "1481789962" , "body" : `Why photography lighting tips are killing you. Why photography tips are killing you. 17 least favorite photo studios. 20 ways photo stocks can find you the love of your life. 17 facts about family portraits that will impress your friends. Nature photographers in 14 easy steps. Ways your mother lied to you about spring pictures. How home photographers can help you predict the future. 13 things about graphic effects your kids don't want you to know. 16 problems with spring pictures.

11 ways wedding pictures could leave you needing a lawyer. The best ways to utilize wedding pictures. How to start using photography ideas. 13 myths uncovered about photo stocks. How baby photos can make you sick. The 8 worst songs about digital cameras. What experts are saying about wedding pictures. Why cutest baby contests are killing you. How not knowing home photographers makes you a rookie. 12 things that won't happen in photography ideas.

14 uses for photography courses. 6 things about photographers your kids don't want you to know. 17 movies with unbelievable scenes about wedding pictures. The best ways to utilize baby photos. 12 facts about beautiful images that'll keep you up at night. Why your nature image never works out the way you plan. Beautiful images in 18 easy steps. How baby photos make you a better lover. 9 great articles about photo awards. Spring pictures in 20 easy steps.

If you read one article about award winning photos read this one. Why the next 10 years of nature images will smash the last 10. 20 amazing cutest baby contest pictures. How family portraits can help you live a better life. 14 things about spring pictures your kids don't want you to know. 6 facts about award winning photos that'll keep you up at night. Why do people think photograph equipment is a good idea? How twitter can teach you about photo awards. The unconventional guide to photographers. How to cheat at photo studios and get away with it.`, "url_img" : "http://3.bp.blogspot.com/-5mF6SoV-9NI/VffQTu_qEFI/AAAAAAAAOek/BrZJp-a9VAk/s1600/photography_foggy-landscape-early-morning_192K.jpg" , "labels" : "Photography, Phone Shots"},

{"title" : "What the world would be like if auto glass didn't exist" , "subtitle" : "11 podcasts about windshield repairs" , "author": "Anselmo Ansélmez" , "date" : "1557044766" , "body" : `How auto repair shops can help you live a better life. Why you'll never succeed at car parts. 15 ways driving experience days can find you the love of your life. Why car accessories are the new black. 12 ways auto paint shops are completely overrated. The 12 best rebuilt engine twitter feeds to follow. How car seat covers are the new car seat covers. 8 podcasts about discount auto parts. How supercars are making the world a better place. Why the next 10 years of hybrid supercars will smash the last 10.

Why you shouldn't eat mechanic shop in bed. Why discount auto parts are killing you. Expose: you're losing money by not using cars. 6 facts about auto accessories that'll keep you up at night. 16 ways car parts are completely overrated. If you read one article about car paint jobs read this one. 16 great articles about automotive museums. Why the next 10 years of car accessories will smash the last 10. 10 podcasts about car companies. 14 secrets about auto accessories the government is hiding.

Why you'll never succeed at car seat covers. How to cheat at exotic cars and get away with it. 7 things you don't want to hear about automotive tires. Auto glass by the numbers. The 17 worst songs about auto repair shops. 7 problems with driving experience days. Why car body shops are afraid of the truth. Unbelievable rebuilt engine success stories. Ways your mother lied to you about auto accessories. Hybrid supercars by the numbers.

18 great articles about auto parts. 14 facts about automotive museums that will impress your friends. Auto paint shops by the numbers. How car accessories aren't as bad as you think. The 8 worst auto warehouses in history. 9 ways cars are completely overrated. How auto accessories can help you live a better life. Supercars by the numbers. 17 ways auto warehouses can make you rich. What experts are saying about auto glass.`, "url_img" : "http://4.bp.blogspot.com/-Y4pM37G7vKE/VfehWAJRN9I/AAAAAAAANd0/aPPpu9QSqXY/s1600/automotive_wob-sc_330K.jpg" , "labels" : "Automotive, Car Shop, Car Accessory"},

{"title" : "How science fair ideas are the new science fair ideas" , "subtitle" : "The evolution of applications" , "author": "Bambarin SF" , "date" : "1463214483" , "body" : `Why operating systems should be 1 of the 7 deadly sins. Why accessories will change your life. How not knowing cool science experiments makes you a rookie. Why home tech gadgets beat peanut butter on pancakes. Why technology tips beat peanut butter on pancakes. How to be unpopular in the accessory world. Why cool tech gadgets are the new black. Open source software by the numbers. The 16 best storage device twitter feeds to follow. Why the world would end without passport applications.

Expose: you're losing money by not using home tech gadgets. What the world would be like if electronic devices didn't exist. How not knowing best stores makes you a rookie. How to cheat at science fair ideas and get away with it. 5 things your boss expects you know about amazing gadgets. 12 things your boss expects you know about technology tips. 6 facts about future technologies that will impress your friends. How business software made me a better person. Why mom was right about science current events. What wikipedia can't tell you about latest electronic gadgets.

Why science fair ideas are the new black. How to cheat at latest electronic gadgets and get away with it. 6 great articles about tech reviews. Unbelievable open source software success stories. 16 ways best stores can find you the love of your life. The 7 biggest amazing gadget blunders. What the world would be like if operating systems didn't exist. How to cheat at science museums and get away with it. An expert interview about storage devices. 12 amazing dollar general application pictures.

The 8 worst computer support specialists in history. The 8 biggest science fact blunders. The 17 best resources for new inventions. The 20 best resources for technology tips. 12 insane (but true) things about open source software. How hollywood got science fair ideas all wrong. Why best stores are killing you. 15 podcasts about devices. Why our world would end if business software disappeared. 10 uses for accessories.`, "url_img" : "http://4.bp.blogspot.com/-uX6aV9khr84/VffTRGn1HmI/AAAAAAAAOs8/4iaLwMcj0ZA/s1600/technology_android-user-with-coffee_043K.jpg" , "labels" : "Technology, Tech Tips, Application"},

{"title" : "Why weight loss success stories are the new black" , "subtitle" : "17 ideas you can steal from fitness programs" , "author": "Rayo McQueen" , "date" : "1526804990 " , "body" : `How cholesterol levels made me a better person. Why online nutrition courses are killing you. Why primary preventions are afraid of the truth. Why health questions should be 1 of the 7 deadly sins. 10 ways healthy eating facts could leave you needing a lawyer. How not knowing weight loss supplements makes you a rookie. The unconventional guide to cholesterol lowering food. Why the world would end without vaccine ingredients. The evolution of weight loss supplements. What everyone is saying about naturopathic medicines.

17 ideas you can steal from cholesterol levels. 9 facts about nutrition facts that'll keep you up at night. 10 ways vaccination schedules could leave you needing a lawyer. How fitness programs can make you sick. 18 things your boss expects you know about online nutrition courses. The 6 best resources for travel medicines. 5 bs facts about fitness equipment everyone thinks are true. How healthy eating facts aren't as bad as you think. 20 ways cholesterol levels can find you the love of your life. How to start using weight loss meal plans.

If you read one article about health quotes read this one. The only relapse prevention worksheet resources you will ever need. Why our world would end if fitness magazines disappeared. The unconventional guide to health informatics. Why mom was right about naturopathic medicines. Why travel vaccines should be 1 of the 7 deadly sins. Why our world would end if health care providers disappeared. 15 uses for healthy eating meal plans. Why nutrition label makers are afraid of the truth. 14 facts about nutrition facts that will impress your friends.

Why cholesterol levels should be 1 of the 7 deadly sins. What the world would be like if travel medicines didn't exist. What wikipedia can't tell you about medicine shops. The 5 worst vaccine ingredients in history. What experts are saying about medicine shops. Will fitness equipment ever rule the world? Why nutrition label makers should be 1 of the 7 deadly sins. The 7 worst songs about primary preventions. Why primary preventions will make you question everything. 15 facts about nutrition facts that will impress your friends.`, "url_img" : "http://3.bp.blogspot.com/-URJQtG4oqqA/VffMDr0_-dI/AAAAAAAAOJM/c7XbnnfcZc8/s1600/health_dumbell-muscle-fit_074K.jpg" , "labels" : "Heath, Nutrition, Medicine, Weight Loss, Vaccines"},

{"title" : "How dance playlists aren't as bad as you think" , "subtitle" : "8 ideas you can steal from music notes" , "author": "El tontico de la clase" , "date" : "1410165136" , "body" : `Why billboard music awards will change your life. 20 problems with rock bands. How to start using summer music festivals. How hot songs can help you predict the future. 11 ways latin instruments can make you rich. How to cheat at concert events and get away with it. 11 podcasts about free dances. How twitter can teach you about billboard music awards. 15 problems with concert tickets. How music notes made me a better person.

The unconventional guide to concert events. Why country music festivals are on crack about country music festivals. If you read one article about rock bands read this one. The 11 worst music scores in history. How concert tickets aren't as bad as you think. The 12 worst songs about latin music videos. 18 insane (but true) things about music festivals. Why mom was right about live shows. 7 least favorite music scores. The oddest place you will find billboard music awards.

What experts are saying about country billboards. 6 things your boss expects you know about free dances. Why do people think country music festivals are a good idea? What experts are saying about latin music videos. Why dance playlists beat peanut butter on pancakes. 6 amazing concert ticket pictures. The oddest place you will find free dances. Why do people think music scores are a good idea? The only dance playlist resources you will ever need. Why the next 10 years of radio stations will smash the last 10.

Why your piano store never works out the way you plan. What the beatles could learn from concert tickets. Why our world would end if radio stations disappeared. 14 facts about billboard alternatives that will impress your friends. 16 myths uncovered about country music festivals. Why our world would end if latin music videos disappeared. The unconventional guide to music videos. 18 ways piano stores can find you the love of your life. 5 things that won't happen in radio stations. 20 things you don't want to hear about best rock songs.`, "url_img" : "http://4.bp.blogspot.com/-XbxAa9s31vU/VffO_2vVPaI/AAAAAAAAOXE/aoRzGuWRoK8/s1600/music_rock-coffee-trends_282K.jpg" , "labels" : "Music, Live Show, Country, Latin, Billboard"},

];
  constructor() { }
}
